__base__:
  - configs/public/deformable_detr_swinB_4lvl_pannuke.yaml
experiment:
  name: defdetr_swinB_4lvl_050mpp_pannuke
  output_name: defdetr_swinB_4lvl_050mpp_pannuke.pth
evaluation:
  max_pair_distance: 6
transforms:
  rescale: 0.5