__base__:
  - configs/public/deformable_detr_swinB_4lvl_S_050mpp_pannuke.yaml
experiment:
  name: defdetr_swinT_4lvl_S_050mpp_pannuke
  output_name: defdetr_swinT_4lvl_S_050mpp_pannuke.pth
model:
  backbone:
    name: swin_T_224_1k